version: '3.7'

services:
  esperluet_api_node_1:    
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '8001:8000'
    container_name: esperluet_api_node_1
    networks:
      - esperluet_network
  esperluet_api_node_2:    
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '8002:8000'
    container_name: esperluet_api_node_2
    networks:
      - esperluet_network
  esperluet_nginx:
    image: nginx
    container_name: esperluet_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=esperluet.local
      - NGINX_PORT=80
    networks:
      - esperluet_network

networks:
  esperluet_network:
    driver: bridge